services:
  app:
    image: ${{ DOCKER_HUB_USERNAME }}/fastfood-bot:latest
    container_name: fastfood-bot
    restart: always
    volumes:
      - logs_volume:/app/logs
    depends_on:
      - db
      - redis
    env_file: .env


  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${{ DB_USER }}
      POSTGRES_PASSWORD: ${{ DB_PASSWORD }}
      POSTGRES_DB: ${{ DB_NAME }}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6380:6379"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${{ RMQ_USER }}
      RABBITMQ_DEFAULT_PASS: ${{ RMQ_PASSWORD }}
    ports:
      - "5674:5672"
      - "15674:15672"


volumes:
  pg_data:
  logs_volume:
