services:
  bot:
    image: ${DOCKER_HUB_USERNAME}/fastfood-bot:latest
    container_name: fastfood-bot
    restart: always
    volumes:
      - ./logs:/bot/logs
    depends_on:
      db_bot:
        condition: service_healthy
      redis_bot:
        condition: service_healthy
    env_file: .env
    networks:
      - fastfood-network


  db_bot:
    image: postgres:15
    container_name: postgres_db_bot
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - pg_data_bot:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fastfood-network

  redis_bot:
    image: redis:7
    container_name: redis_bot
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - redis_data_bot:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fastfood-network

  loki_bot:
    image: grafana/loki:latest
    container_name: loki_bot
    ports:
      - "3102:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - fastfood-network

  promtail_bot:
    image: grafana/promtail:latest
    container_name: promtail_bot
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs:/bot/logs
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - fastfood-network

  grafana_bot:
    image: grafana/grafana:latest
    container_name: grafana_bot
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED: false
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - fastfood-network

volumes:
  pg_data_bot:
  redis_data_bot:

networks:
  fastfood-network:
    external: true