server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_bot:3100/loki/api/v1/push

scrape_configs:
  - job_name: errors_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: errors_logs
          __path__: /logs/errors/*.txt

  - job_name: general_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: general_logs
          __path__: /logs/general/*.txt