server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_bot:3100/loki/api/v1/push

scrape_configs:
  - job_name: bot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: bot
          log_type: general
          __path__: /bot/logs/general/*.log

      - targets:
          - localhost
        labels:
          job: bot
          log_type: error
          __path__: /bot/logs/error/*.log